### ISSUE TITLE
color clip outputs some strange holes

### ISSUE THREAD

**Issue by Rvage0815** [bmad4ever/comfyui_bmad_nodes#13] opened 2024-04-08 09:16 UTC
color clip outputs some strange holes.
![Screenshot 2024-04-08 111325](https://github.com/bmad4ever/comfyui_bmad_nodes/assets/155462691/22b69aaa-9624-4dbd-81ea-6c9796abec42)

**Comment by bmad4ever** [comment] 2024-04-08 15:02
Hi,

**Can you share the image in the preview so I can test it locally?**

It may be the case that the area has slight variations in color, but I can't know if this is the case before testing and reviewing the code; if this is the case since color clip doesn't use a range or error margin, you can use a closing morphologic operation to remove the holes ( there is both: a comfyui node for this, and another one in bmad's custom nodes ).
Alternatively, still under the supposition that the problem is caused by non-uniform coloring, you may search for a custom node that allows to specify an error margin.

If you are only segmenting people, I also advise checking other alternative nodes for the job, such as  https://github.com/ltdrdata/ComfyUI-Impact-Pack SEGS nodes. 

Kind Regards.

**Closed** 2024-06-11 20:09 UTC
